---
Token: "<discord bot token>"
MariaDb:  "<user>:<password>@tcp(<MariaDB IP>:<MariaDB Port>)/"
RemoveImages: false
ForceReload: false
Timeout: 10
SteamApiKey:  "<Steam Api Key>"
SteamApi: "https://api.steampowered.com"
SteamUser: "ISteamUser"
SteamApiVersion: "V001"
Dota2Match: "IDOTA2Match_570"
Dota2Econ: "IEconDOTA2_570"
Dota2ApiVersion: "V001"
